### ISSUE TITLE
Elegir dominio canónico

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io#11]
Ahora mismo tanto pybonacci.org como pybonacci.es funciona. Creo que deberíamos tener **un solo** dominio canónico que usemos siempre, y redireccionar el otro cambiando la URL.

Propuesta: pybonacci.org.

Las URLs de pybonacci.es deberían cambiar a pybonacci.org.

@kikocorreoso Si no te parece bien la propuesta también podemos hacerlo al revés. Me es indiferente, pero aun así prefiero que tengamos un solo dominio.

cc @Pybonacci/administradores

**Comment by manugarri** [comment]
:+1: a pybonacci.org

**Comment by kikocorreoso** [comment]
+1 al +1 de @manugarri

**Comment by Juanlu001** [comment]
En progreso.

**Comment by Juanlu001** [comment]
Ya he redirigido el .es al .org, el cambio tardará en propagarse unas horas.
