### ISSUE TITLE
Añadir entradas que faltan

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io#12]
Ahora mismo hay cuatro (?) entradas de @kikocorreoso que están en el blog de WordPress y que no están aquí. Es normal, porque la importación la hice hace tiempo. Deberíamos actualizar las fuentes de Pelican.

@kikocorreoso las entradas son todas tuyas, pero si no tienes tiempo te puedo ayudar migrando la mitad. Me dices lo que sea.

cc @Pybonacci/editores

**Comment by kikocorreoso** [comment]
Dejadme aterrizar. Tengo bastante lío.

Desplegad lo que sea y yo actualizaré, aunque sea a mano, cuando pueda... Mientras esté todo bien documentado, que es lo más importante, lo demás será relativamente sencillo.

**Comment by Juanlu001** [comment]
Sin problema. De momento lo voy a dejar en este hito, si no llegas por lo que sea lo pasamos al siguiente. Aún queda un mes :)

**Comment by Juanlu001** [comment]
Todas las tareas críticas de https://github.com/Pybonacci/pybonacci.github.io/milestone/1 están solventadas, a falta de que la transmisión de new.pybonacci.org se haga efectiva. Ya se pueden arreglar las entradas existentes, y cuando eso esté se puede hacer #13 y dar paso al nuevo Pybonacci. Me gustaría tener algún tipo de analíticas #5 pero si no queda más remedio lanzaremos sin eso.

**Comment by manugarri** [comment]
@Pybonacci/administradores hace falta exportar las entradas que quedaron pendientes de WP? si me dais acceso las exporto yo aunque sea haciendo copypaste y editando a mano

**Comment by Juanlu001** [comment]
@manugarri si tienes Signal o GPG te paso la clave de administración, hablamos en privado.

**Comment by manugarri** [comment]
Me pongo con esto.

**Comment by manugarri** [comment]
Resuelta en https://github.com/Pybonacci/pybonacci.github.io/pull/59 @kikocorreoso todos los articulos son tuyos, si puedes por favor echales un vistazo.

Creo que deberiamos imponer un tamaño minimo de imagen. Por ejemplo en el articulo de Folium (2017/09/07/como-crear-un-mapa-interactivo-con-folium/)  las imagenes son muy pequeñas (300x147), asi que obligan a meter custom css simplemente por que son más pequeñas que el width del articulo, y si las hacemos mas grandes se van a ver pixeladas.

Como apaño y para no tener que modificar el css a pelo (que en wordpress está gestionado especificando un width y height especifico), he añadido al main.less el bloque:

```
img[src$="centerme"] {
  display:block;
  margin: 0 auto;
}
```

Asi que a partir de ahora, si queremos mostrar una imagen centrada, podemos hacer:

```
![](https://www.pybonacci.org/images/2017/09/mapa3-300x147.png?style=centerme)
```

De todas formas voy a añadir un issue para darle caña al css.

**Comment by Juanlu001** [comment]
Lo que ha avanzado el CSS en los últimos años... Bueno gente, ya tenemos las entradas gracias a @manugarri (#59) así que voy a cerrar esto por fin. Si hay algo raro, pull request :wink:

**Comment by manugarri** [comment]
pues si, de todas maneras hay que darle un poco de amor al css

**Comment by kikocorreoso** [comment]
Gracias.

Sí, molaría trabajar el CSS un poco para arreglar cositas.

@manugarri creas un TO-DO para cosas del css que hayas ido viendo, @Juanlu001 lo mismo, y sobre ese TO-DO vamos creando y resolviendo issues?

**Comment by manugarri** [comment]
roger
