### ISSUE TITLE
Redireccionar dominio a pybonacci.github.io

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io#16]
:warning: Hacer **al final** del milestone, cuando todo esté listo.

**Comment by kikocorreoso** [comment]
¿Desplegamos en mi servidor?

Podemos centralizar despliegue, analítica, comentarios,...

Evitamos que terceros sepan quién visita qué (cada día que pasa es más importante para mí esto).

**Comment by Juanlu001** [comment]
Por mi parte ningún problema. Podemos usar `pybonacci.github.io` como área de pruebas entonces. Lo único es que me gustaría que nos dieras acceso fácil a los demás para ver analíticas y demás :)

Para ideas sobre cómo desplegar en un servidor externo:

https://github.com/python-spain/web/blob/da2b40b/deploy.sh

**Comment by kikocorreoso** [comment]
Yo no tengo ningún problema en que las analíticas sean 100% públicas. Se pueden commitear diariamente, semanalmente,..., los logs al repo de turno. Entiendo que se podría considerar seguro previa censura de alguna información relevante o personal. También puedo currarme las analíticas chulas y visuales en un dashboard (milestone 321.0).

Tampoco tengo ningún problema en que costeemos un VPS pybonacci python friendly (pythonanywhere, webfaction,... ) entre todos y todos tengamos acceso y capacidad de romperlo 💔

**Comment by manugarri** [comment]
> Tampoco tengo ningún problema en que costeemos un VPS pybonacci python friendly (pythonanywhere, webfaction,... ) entre todos y todos tengamos acceso y capacidad de romperlo :broken_heart:

En cuanto a esto, y quizas es una pregunta totalmente distinta, podriamos pedir ayuda de financiacion a Python España?

**Comment by kikocorreoso** [comment]
>> Tampoco tengo ningún problema en que costeemos un VPS pybonacci python friendly (pythonanywhere, webfaction,... ) entre todos y todos tengamos acceso y capacidad de romperlo :broken_heart:

>En cuanto a esto, y quizas es una pregunta totalmente distinta, podriamos pedir ayuda de financiacion a Python España?

Desde mi punto de vista, sería a 1 €/mes por editor. Tampoco veo cómo justificar que nos den a nosotros o a otros 100000 más. No hay un procedimiento claro. Podría ser una beca por difundir python es español o algo así pero no existe. Se les puede plantear.

Independientemente, si el dinero es un problema sigo aportando mi servidor sin problemas. Solo que no os puedo dar claves ya que tengo otras cosas ahí metidas. Lo de un VPS nuevo sería para que todos tengamos acceso.

**Comment by Juanlu001** [comment]
> En cuanto a esto, y quizas es una pregunta totalmente distinta, podriamos pedir ayuda de financiacion a Python España?

Nunca se ha hecho, pero puedo hablar con el presidente... :stuck_out_tongue:

**Comment by manugarri** [comment]
lol, por eso decía, no sé si viola el Codigo de Conducta XD
