### ISSUE TITLE
Pelican-plugins config está roto.

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io#24]
Al actualizar los submodulos de pelican, hay una referencia a `bootstrap-rst` que no existe:

Estamos referenciando directamente el pelican plugins .config de [Pelican directamente] (https://github.com/getpelican/pelican-plugins/blob/76a8be9978bcfddc6dcf05678420fb06ee32cb0d/.gitmodules#L126)

[He puesto un issue en pelican-plugins](https://github.com/getpelican/pelican-plugins/issues/941), con suerte lo arreglaran pronto. En caso contrario tendriamos que eliminar la referencia.

**Comment by manugarri** [comment]
Esto tiene prioridad BAJA

**Comment by Juanlu001** [comment]
Arreglado.
