### ISSUE TITLE
Habilitar HTTPS usando CloudFlare

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io#34]
https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by Juanlu001** [comment]
Esto lo dejo para el siguiente hito, cuando dejemos estables los DNS, para que no haya problemas. Lo haré una semana después de que tengamos anuncio oficial.

**Comment by kikocorreoso** [comment]
He habilitado 'Enforce HTTPS' para las *github pages* en los *settings* del repo.

https://help.github.com/articles/securing-your-github-pages-site-with-https/

No sé si eso es suficiente de momento. Si es así, cierra el issue.

**Comment by Juanlu001** [comment]
Ahora hay warnings de mixed content, hay que limpiar enlaces https://new.pybonacci.org/

**Comment by kikocorreoso** [comment]
Leo [aquí](https://blog.securem.eu/serverside/2018/04/18/github-pages-generated-a-tls-cert-for-my-own-domain/) (el 4º párrafo empezando por el final) que GH va ha añadir certificados para las Pages: https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8#gistcomment-2370070

**Comment by Juanlu001** [comment]
¡Genial! Nos podemos relajar entonces :)

**Comment by kikocorreoso** [comment]
Lo cierro. Si alguien considera que falta algo que lo reabra.
