### ISSUE TITLE
Resaltado de código un poco aleatorio

### ISSUE THREAD

**Issue by kikocorreoso** [Pybonacci/pybonacci.github.io#35]
He visto que para ciertos posts el código sale resaltado mientras que para otros no es así. Habría que investigar como hacer que esto sea más determinista.

**Comment by Juanlu001** [comment]
¿Qué posts?

**Comment by manugarri** [comment]
estoy de acuerdo. Puede haber dos causas:

- Posts auto generados que no referencian el sistema de pelican de resaltado de sintaxis (el antiguo >pre>code> no funciona con pelican). Esto se arreglará revisando caso a caso.
- El sistema de resaltado de Pelican no es muy potente incluso cuando reconoce el lenguaje. Esto habria que mirar si queremos usar una libreria distinta para el resaltado (que meteria js , cosa innecesaria creo yo).

**Comment by manugarri** [comment]
Bueno, segun parece la mejor manera de asegurarse de que el codigo se resalte es removiendo los `pre>code` e indentando el snippet de còdigo 4 espacios.

Asi:

    :::python
    import pandas as pd
    df = pd.read_clipboard()


Se resalta correctamente. En caso de que se quiera hacer un snippet de codigo sin ningun resaltado, se puede hacer asi:

    :::
    este codigo se resalta como codigo
    pero ninguna palabra tiene un color distinto

**Comment by manugarri** [comment]
creo que esta la podemos cerrar, no @kikocorreoso ?

**Comment by kikocorreoso** [comment]
Lo dejo abierto para ver si tengo tiempo de crear un script para parsear todos los md y que cambien el `pre>code` con `:::`.

Me lo asigno.

**Comment by manugarri** [comment]
uuff, no sé si eso funcionará, por lo que he estado viendo el html producido por la herramienta de wp no es super estable. Se puede probar, eso si.

**Comment by manugarri** [comment]
@kikocorreoso voy a echarle un ojo este finde a ver si hago el script, que en principio solo habria que ejecutar una vez.

**Comment by manugarri** [comment]
Creada PR https://github.com/Pybonacci/pybonacci.github.io/pull/55 

@kikocorreoso  esto no está relacionado, pero me he dado cuenta de que la entrada `/2016/02/14/formula-para-el-amor/` no tiene imagen, el articulo original tenia imagen?.

**Comment by kikocorreoso** [comment]
@manugarri

Según esto no había imagen: https://old.pybonacci.org/2016/02/14/formula-para-el-amor/

**Comment by manugarri** [comment]
pues si https://github.com/Pybonacci/pybonacci.github.io/pull/55 está bien , yo creo que esta se puede cerrar, no @Pybonacci/administradores ?

**Comment by Juanlu001** [comment]
Cerrando!
