### ISSUE TITLE
Link a Licencia está roto

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io#37]
El link en el footer que redirige a la licencia del blog (LICENSE.md) (https://github.com/Pybonacci/pybonacci.github.io/blob/master/LICENSE.md) está roto

**Comment by manugarri** [comment]
https://github.com/Pybonacci/pybonacci.github.io/pull/38

**Comment by Juanlu001** [comment]
Arreglado en #39.
