### ISSUE TITLE
Imágenes rotas cuando se redireccionen dominios

### ISSUE THREAD

**Issue by kikocorreoso** [Pybonacci/pybonacci.github.io#40]
Ahora mismo, las imágenes que están alojadas en el wordpress se romperán en cuanto actualicemos dominios. Ejemplo:

https://github.com/Pybonacci/pybonacci.github.io/blame/sources/content/articles/2012-05-19-manual-de-introduccion-a-matplotlib-pyplot-ii-creando-y-manejando-ventanas-y-configurando-la-sesion.md#L72

Eso apunta al wordpress y cuando lo movamos a old.pybonacci.org se van a romper todas las imagenes.

¿Opciones?
* Guardar las imágenes en el repo y enlazar correctamente. :+1: 
* Actualizar todos los dominios para que apunten a old :-1:

**Comment by Juanlu001** [comment]
La primera opción puede llevar un poco más de tiempo. ¿A lo mejor se puede hacer primero la segunda y luego la migración al repositorio? Habrá que hacer algún script o algo, no es trivial.
