### ISSUE TITLE
Para justo antes de redireccionar el dominio ejecutar utilities/fix_img_links.py

### ISSUE THREAD

**Issue by kikocorreoso** [Pybonacci/pybonacci.github.io#41]
Ahora, todos los enlaces son absolutos y están apuntando a `new.pybonacci.org`.

Antes de redireccionar el dominio de `pybonacci.org` a github.io habra que ejecutar `utilities/fix_img_links.py` para volver a corregir las urls de las imágenes. Se crea un backup para cada fichero *.md* pero se puede comentar la línea si eres un aventurero.

**Comment by kikocorreoso** [comment]
@manugarri @Juanlu001 

Esto se debería ejecutar justo antes de ponerlo en producción. Lo único que hace es buscar enlaces con new.pybonacci.org y cambiarlos a pybonacci.org.

Otra cosa mejor sería usar enlaces relativos pero la conversión ya los hizo así. BTW, ¿Quién hizo la conversión de WP a .md?

**Comment by Juanlu001** [comment]
Creo que usé `pelican-import`, si no recuerdo mal http://docs.getpelican.com/en/3.7.1/importer.html

**Comment by manugarri** [comment]
@ya lo he ejecutado en https://github.com/Pybonacci/pybonacci.github.io/pull/58, podemos cerrar esta issue cuando se apruebe la otra PR

**Comment by Juanlu001** [comment]
¡Cerrando!
