### ISSUE TITLE
Latex no renderiza correctamente

### ISSUE THREAD

**Issue by kikocorreoso** [Pybonacci/pybonacci.github.io#42]
Por ejemplo:

http://new.pybonacci.org/2012/09/14/calculando-cuantiles-con-python/

Hay fórmulas entre `$...$` en el *.md* que no se transforman en el *.html*.

He estado viendo como solucionarlo pero no he visto cómo.

**Comment by manugarri** [comment]
ya veo, como gestionabamos eso en Wordpress? A lo mejor podemos usar [este plugin](https://github.com/getpelican/pelican-plugins/tree/master/render_math) de pelican? Usa mathjax por debajo que es lo mismo que usa Jupyter (por lo que deberia funcionar en principio)

**Comment by kikocorreoso** [comment]
Ya usamos un plugin, el que usa jakevdp, pero no sale bien lo del latex. Le eché un ojo en su momento pero como estamos usando el flujo de trabajo de otro no es algo de tres minutos. Hay que buscar bien porqué no lo hace bien a nosotros y a él sí si usamos lo mismo...

**Comment by Juanlu001** [comment]
A él también le ha dejado de funcionar...

http://jakevdp.github.io/blog/2012/12/19/sparse-svds-in-python/

https://github.com/jakevdp/jakevdp.github.io-source/issues/4

Creo que es porque MathJax está tratando de cargar las fuentes a través de HTTP.

**Comment by Juanlu001** [comment]
Creo que basta con poner la configuración *antes* que la carga, como está hecho aquí:

https://github.com/csrgxtu/blog-hexo-src/blob/478b0007b53e321d0bed44489c7d3d4c292cd1bb/themes/yilia/layout/_partial/mathjax.ejs

Por tanto habría que tocar esto:

https://github.com/Pybonacci/pybonacci.github.io/blob/sources/theme/templates/base.html#L25-L44

**Comment by manugarri** [comment]
ok parece un easy fix (si el fix propuesto en el repo de mathjax funciona), os parece que me lo asigne o hay alguien ya mirandolo?

**Comment by Juanlu001** [comment]
lo primero es que alguien lo pruebe, si tienes un rato adelante!

**Comment by manugarri** [comment]
fix aquí https://github.com/Pybonacci/pybonacci.github.io/pull/48

Basicamente, el snippet que ha subido @Juanlu001 .
