### ISSUE TITLE
Revisar Entradas Autogeneradas

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io#45]
Tenemos que revisar las entradas que se autogeneraron automáticamente. En particular hay que revisar los siguientes aspectos (lista no exhaustiva):

- Renderizado de Código
- Links a assets (imágenes), de momento se pueden dejar referenciando la version de Wordpress.

Yo revisaré mis entradas otra vez por si acaso (aunque ya lo hice nunca está de más). De todas formas podemos repartirnos entre los que tengamos menos carga de trabajo la revisión del resto de entradas para acelerar la salida de la nueva versión cuanto antes.

@Pybonacci/editores podeis ir indicando si habeis revisado vuestras entradas?

**Comment by Juanlu001** [comment]
Yo en mayo iré revisando las mías. Los links a los assets ¿los cambiamos a `old.pybonacci.org`?

**Comment by kikocorreoso** [comment]
Yo estoy referenciando a new.pybo (aunque queden cosas inútiles como `alt="...wp-content/..."` en las figuras que tendré que borrar porque la conversión ha dejado mucha mierda). Es decir, si es una figura pongo el `src` apuntando a new.pybo. Cuando lo pongamos en producción antes habrá que pasar https://github.com/Pybonacci/pybonacci.github.io/tree/sources/utilities

**Comment by kikocorreoso** [comment]
Respecto a la revisión de mis entradas, he revisado muchas, pero no todas. Algunas las revisaré de nuevo para eliminar mierda pero no sé si queremos algunos estándares con algunas cosas. Lo podemos hablar en algún canal.

**Comment by manugarri** [comment]
comprendido , entonces me toca cambiar los src de mis articulos a new.pybonacci.org. La semana que viene tengo hueco y creo que podre revisar un buen numero de articulos

**Comment by kikocorreoso** [comment]
No hace falta cambiar las urls mientras apunten bien a una url del futuro (sin `new.`) ya que el script solo actualizaría las que tengan `new.pybonacci.org`. Es decir, si ya las cambiaste para que funcionasen para `pybonacci.org` las puedes dejar. En el futuro podemos pasar algo para cambiarlas todas a relativas y no tener este problema.

**Comment by AlexS12** [comment]
Me encargo de echar un vistazo al menos a las mías la semana que viene

**Comment by manugarri** [comment]
una duda @kikocorreoso , en pybonacci.org, en el [articulo](http://localhost:8000/2015/12/11/breve-introduccion-a-los-sistemas-de-recomendacion/) sobre sistemas de recomendacion, veo que la url de una imagen https://core0.staticworld.net/images/article/2015/03/netflixpregodmode-100574324-orig.png

Ahora en el repo está como:  

http://core0.staticworld.net/http://new.pybonacci.org/images/article/2015/03/netflixpregodmode-100574324-orig.png

Que no funciona ahora mismo. Esta ultima url es correcta? A que debería cambiarla?

**Comment by kikocorreoso** [comment]
@manugarri te invoco!!!

Ese artículo es de manu. Lo mejor es que empecemos a dejar de hacer hotlinking y hospedemos nosotros mismos todos los assets que estén en nuestras manos, referenciando a sus fuente, of course.

**Comment by manugarri** [comment]
@kikocorreoso coñe ya lo sé, si lo he comentado yo! 

Que es lo mejor, añado la imagen al repo directamente?  

Veo que en el repo hay un listado de carpetas con imagenes en https://github.com/Pybonacci/pybonacci.github.io/tree/sources/content/images , hay alguna manera de añadirlas ahi automaticamente al hacer `make html`?

**Comment by kikocorreoso** [comment]
@manugarri Jajajajaja, sí, es que me ha llegado al correo y estaba en un hilo en el que estaba también @AlexS12 y me he confundido pensando que era de @AlexS12 la pregunta.

Esto de leer en diagonal...

Habrá que colocar las imágenes en la carpeta correcta y usar enlaces relativos como comenté en otro hilo.  Pero nos tocará tocar alguna cosa o rehacer todos los enlaces absolutos...

**Comment by manugarri** [comment]
@kikocorreoso ok, veo como linkear la imagen manualmente

**Comment by manugarri** [comment]
arreglado kiko, basicamente he subido la imagen a `content/images/2015/12/netflixpregodmode-100574324-orig.png`

Y referenciado asi en el articulo:

![netflix](/images/2015/12/netflixpregodmode-100574324-orig.png)

**Comment by kikocorreoso** [comment]
:+1:

**Comment by Juanlu001** [comment]
Creo que @manugarri ya ha revisado las suyas, así que cambio aquí los asignees para que no se nos olvide.

**Comment by Juanlu001** [comment]
Esto es un no-issue, porque no hay una tarea concreta. Ya se pasó el momento de "revisar", ahora si alguien en algún momento ve algún problema concreto ya lo puede arreglar.
