### ISSUE TITLE
Pybonacci 3.0

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io#54]
1. [ ] #12
2. [ ] #5?
3. [ ] #13
4. [ ] #41

¡Y redireccionar!

**Comment by manugarri** [comment]
#12 es el cuello de botella imagino.

yo creo que #5 no es necesaria para el primer release, no? Es decir, imagino que no es trivial montarlo y siempre se puede añadir a posteriori

#13 creo que  @kikocorreoso lo tiene hecho no? una historia sobre el origen de pybonacci.

#41 imagino que es solo ejecutar un script cuando este todo listo y revisar las entradas?

**Comment by kikocorreoso** [comment]
#12 No hay muchas entradas que falten. Serán 3 o 4.

#5 Lo hemos estado usando en pybonacci-WP y no creo que vaya muy fino. El número de visitas que da piwik es un orden de magnitud menor que el que daba WP-stats. Lo puse en marcha en poco tiempo montando Piwik en mi servidor y usando un plugin de WP e igual hay algo que está mal. Si alguien tiene experiencia con ello se agradece que lo mire.

#13 Podemos meter la chicha sobre cómo contribuir en aquello que escribimos (¿pybo3.0 se llamaba?). Entiendo que sería añadir el CONTRIBUTING.md al notebook aquel. Me lo echo yo sobre la chepa.

#41 debería ser cómo dice @manugarri

**Comment by manugarri** [comment]
como vamos @Pybonacci/administradores  ? Hay algun issue en el que pueda ayudar?

**Comment by Juanlu001** [comment]
Voy atrasado con hacer los cambios en el DNS, pero creo que lo conseguiré antes de que acabe la semana

**Comment by Juanlu001** [comment]
Redirigiendo

**Comment by Juanlu001** [comment]
Redirección hecha, en 24 horas debería poder arreglar los errores de SSL

![screenshot-2018-6-24 pybonacci pybonacci github io](https://user-images.githubusercontent.com/316517/41819866-82db9c4e-77c8-11e8-9202-f9d271802992.png)

**Comment by Juanlu001** [comment]
Ahora un poco de turbulencia hasta que se propaguen los cambios en los DNS y en unas horas debería estar todo resuelto. El blog antiguo está ahora aquí:

https://old.pybonacci.org/

Voy a cerrar este meta-issue y comentar en el resto.
