### ISSUE TITLE
Error de latex? o error de articulo?

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io#56]
@kikocorreoso  En el articulo 2012-10-18-calculando-cosas-mientras-jugamos-a-la-ruleta.md El latex se imprime de forma un poco caotica.

![image](https://user-images.githubusercontent.com/3670355/43390241-fc3e7e58-93ed-11e8-879a-54ab26e8db0a.png)

**Comment by Juanlu001** [comment]
Creo que faltan contrabarras: https://github.com/Pybonacci/pybonacci.github.io/blame/sources/content/articles/2012-10-18-calculando-cosas-mientras-jugamos-a-la-ruleta.md#L46

**Comment by manugarri** [comment]
no me queda claro @Juanlu001 , en la L46 es un bloque de python, no deberia afectar al r esto de markdown, no?

**Comment by Juanlu001** [comment]
Ha cambiado la línea porque hice merge de tus pull requests después :) Es esto:

https://github.com/Pybonacci/pybonacci.github.io/blame/sources/content/articles/2012-10-18-calculando-cosas-mientras-jugamos-a-la-ruleta.md#L50-L54

**Comment by manugarri** [comment]
Parece que es algo que habrá que ver caso por caso, ya que WP se ha pulido las barras de LaTex.

`$Area\_{text{poligono interior}} = Area\_{text{poligono exterior}}frac{text{cont}}{text{num pruebas}} $`

No se renderiza bien.

`$Area_{\text{poligono interior}} = Area_{\text{poligono exterior}}\frac{\text{cont}}{\text{num pruebas}}$`

Si se renderiza correctamente.

Como nota, he mirado la documentacion de pelican [render_math](https://github.com/getpelican/pelican-plugins/tree/master/render_math) y pone: 
>Math between $..$, for example, $x^2$, will be rendered inline with respect to the current html block. Note: To use inline math, there must not be any whitespace before the ending $. So for example:

    Relevant inline math: $e=mc^2$
    Will not render as inline math: $40 vs $50

Puede ser un error (adicional)

**Comment by manugarri** [comment]
chapo, en cuanto al latex los errores que vayan apareciendo los podemos poner en issues separadas.
