### ISSUE TITLE
Imagenes no se muestran

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io#57]
@kikocorreoso no estoy seguro de si este error es por lo de ejecutar el script de arreglar imagenes, pero en el articulo https://www.pybonacci.org/2012/07/01/manual-de-introduccion-a-matplotlib-pyplot-vi-tipos-de-grafico-iii/ las imagenes no se muestran pese a que las imagenes [existen](htttp://new.pybonacci.org/images/2012/07/tricontornos.png)

**Comment by manugarri** [comment]
por lo que veo, el exportador de WP ha convertido las imagenes en el formato 

```
[<img class="aligncenter  wp-image-672" title="tricontornos" src="http://new.pybonacci.org/images/2012/07/tricontornos.png" alt="" width="652" height="553" srcset="https://pybonacci.org/wp-content/uploads/2012/07/tricontornos.png 652w, https://pybonacci.org/wp-content/uploads/2012/07/tricontornos-300x254.png 300w" sizes="(max-width: 652px) 100vw, 652px" />](http://new.pybonacci.org/images/2012/07/tricontornos.png)
```
O sea, html dentro de markdown, great!.

Voy a ver si hago otro script de regex (sigh) para convertir esas imagenes en algo del tipo: [tricontornos](http://new.pybonacci.org/images/2012/07/tricontornos.png)

@Pybonacci/administradores os parece que haga algo asi? o preferis que mantenga el custom css de cada imagen? En principio yo preferiria matar el css customizado de cada imagen (flexibilidad, simplicidad, y visibilidad en moviles), pero es una opinion totalmente debatible.

**Comment by manugarri** [comment]
Posible arreglo en https://github.com/Pybonacci/pybonacci.github.io/pull/58

**Comment by Juanlu001** [comment]
El enlace está, pero faltan aún las imágenes.

**Comment by Juanlu001** [comment]
Las imágenes aún no se muestran. Por otro lado, los enlaces a `new.pybonacci.org` dan error de mixed content, así que posiblemente tengamos que cambiarlos a `www.pybonacci.org`.

https://www.pybonacci.org/2012/07/01/manual-de-introduccion-a-matplotlib-pyplot-vi-tipos-de-grafico-iii/

**Comment by Juanlu001** [comment]
Estoy diciendo tonterías: lo de `new` ya se arregló. Aunque el HTML parece que está bien:

https://github.com/Pybonacci/pybonacci.github.io/blob/be16bde7485179b2711beba11f63ac5d6e87993c/2012/07/01/manual-de-introduccion-a-matplotlib-pyplot-vi-tipos-de-grafico-iii/index.html#L532

Aún no lo veo en la web, y eso que he esperado unos minutos. Si alguien mira esto y ve que ya está arreglado, que cierre - si no, hay algún problema en algún lado.

**Comment by Juanlu001** [comment]
¡Ya se muestran! Cerrando :tada:

**Comment by manugarri** [comment]
excellent.
