### ISSUE TITLE
Cambios de estilo

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io#62]
(Sigue de https://github.com/Pybonacci/pybonacci.github.io/issues/12#issuecomment-410501665)

Mi mayor problema con el estilo actual es que, con el nivel de zoom por defecto, el texto se ve enorme. En el móvil el efecto se nota especialmente:

![screenshot_2018-08-06 inicio pybonacci](https://user-images.githubusercontent.com/316517/43730135-a4c97b38-99aa-11e8-9015-52ec9b5ee9fd.png)

Pero seguro que al resto se le ocurren más cosas.

**Comment by kikocorreoso** [comment]
¿Esto es bloqueante para lanzar oficialmente pybo 3.0? No sé si lo hemos hecho muy oficial y teníamos un notebook pendiente por ahí que ya revisamos (por pybocorreo) de 'Bienvenido a Pybonacci 3.0.0' que me gustaría lanzar para oficializar un poco el tema del 3.0.0.

Le pongo milestone para pybo 3.1 a este issue. Si preferís cambiarlo hacedlo.

**Comment by Juanlu001** [comment]
Bloqueemos lo menos posible, sí!

**Comment by manugarri** [comment]
Le echo un ojo, usamos em para hacer las fuentes mas grandes, seguro que usando less podemos usar webkit o algo de media queries para que el tamaño de la fuente se adapte a mobile.

De todas formas lo suyo seria que hiciesemos un sprint en la pycon como el año pasado, este tema de tamaños de fuente y estilo me parece que a) es algo subjetivo y b) no creo que sea el expertise de ninguno de nosotros.

**Comment by manugarri** [comment]
echadle un ojo a esta pr que puede ayudar a arreglar el tamaño de fuente https://github.com/Pybonacci/pybonacci.github.io/pull/69

**Comment by manugarri** [comment]
@Juanlu001 mergeamos el cambio de css y parece que hace la fuente mas pequeña, que te parece?

**Comment by Juanlu001** [comment]
Cerrrando!
