### ISSUE TITLE
Primera entrada sobre Machine learning no se sigue

### ISSUE THREAD

**Issue by kikocorreoso** [Pybonacci/pybonacci.github.io#65]
Un lector nos manda un correo dónde nos indica que que esta entrada tiene varios errores:

https://github.com/Pybonacci/pybonacci.github.io/blob/sources/content/articles/2015-01-14-introduccion-a-machine-learning-con-python-parte-1.md

* No se indica de dónde sale el *iris dataset*. Podemos actualizarlo usando `load_iris` de sklearn. Al no saberse de dónde salen los datos algún código no es fácil de seguir (ej.; `iris = iris[iris.Name != 'Iris-setosa']`).
* Algunos símbolos no se han convertido correctamente al pasar de WP a Pelican (ej, `&lt;` en lugar de `<`).

cc @pfsq ¿tendrías el notebook y el *iris.csv* que usaste para poder actualizarlo?

**Comment by pfsq** [comment]
OK; le echo un vistazo.

**Comment by kikocorreoso** [comment]
Solucionado!!
