### ISSUE TITLE
Travis no renderiza notebooks

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io#74]
Usando el environment yml del repo para instalar el entorno conda, pelican correctamente convierte los articulos que son notebooks.

Sin embargo, travis-ci esta fallando al generar esos articulos ([ejemplo de build fallido](https://travis-ci.org/Pybonacci/pybonacci.github.io/jobs/438241965#L763))

Creo que debe ser un problema de paquetes, ya que en local usamos conda y travis usa pip, por lo cual es posible que el versionado sea distinto

**Comment by manugarri** [comment]
Pongo el stacktrace aqui
```

ERROR: Could not process articles/2016-02-22-el-producto-de-matrices-y-el-nuevo-operador.md
  | TypeError: store() got an unexpected keyword argument 'safe'
ERROR: Could not process articles/2015-01-05-ecuaciones-de-lotka-volterra-modelo-presa-depredador.md
  | TypeError: store() got an unexpected keyword argument 'safe'
ERROR: Could not process articles/2018-03-27-performance-pandas-numpy-bottleneck.md
  | TypeError: store() got an unexpected keyword argument 'safe'
Done: Processed 189 articles, 0 drafts, 2 pages and 0 hidden pages in 9.51 seconds.
```

Parece que el error est'a en este [plugin de pelican](https://github.com/getpelican/pelican-plugins/blob/0b3b844c0e4b88abc4549b29e8bee1c7fd1597fc/liquid_tags/notebook.py#L347)

**Comment by manugarri** [comment]
El issue al respecto [se abrio hace 3 dias ](https://github.com/getpelican/pelican-plugins/issues/1069)

**Comment by manugarri** [comment]
Travis ha funcionado correctamente ahora!.

**Comment by manugarri** [comment]
Ahora travis funciona y crea el contenido, de hecho el contenido de los articulos de notebooks aparece en su carpeta como el resto y hasta  [hasta en el html del indice del blog](https://github.com/Pybonacci/pybonacci.github.io/blob/master/index.html#L601), sin embargo, los articulos con notebooks no aparecen.

**Comment by Juanlu001** [comment]
No puedo reproducir el error localmente

**Comment by manugarri** [comment]
yo tampoco :(, en local va bien. Lo unico que se me ocurre es que sea algun tema de GH pages (ayer estaba de mantenimiento)

**Comment by manugarri** [comment]
Efectivamente, era un fallo de github pages, [ahora se muestran los notebooks](https://www.pybonacci.org/2018/03/27/performance-pandas-numpy-bottleneck/)

que bien todo, chapo el issue
