### ISSUE TITLE
Un único revisor

### ISSUE THREAD

**Issue by kikocorreoso** [Pybonacci/pybonacci.github.io#77]
De cara a agilizar algunas cosas y a que todos somos adultos hemos hecho lo siguiente:

@manugarri y @AlexS12 son admin además de @Juanlu001 y @kikocorreoso 

¿Bajamos los revisores de 2 a 1 para que no haya cuello de botella?

**Comment by manugarri** [comment]
+1 por mi

**Comment by Juanlu001** [comment]
+1

**Comment by manugarri** [comment]
chapamos issue?

**Comment by kikocorreoso** [comment]
Modificado.
